def makeBreakFast(item):
    print (item)

makeBreakFast('PREPARE THE INREGEDIENTS','GET THE INGREDIENTS''MIX THEM','PREPARE THE PAN','PLACE ON THE STOVE',
'POUR THE MIXTURE ON THE STOVE','HEAT IT UP AND TURN IT THE OTHER SIDE TO HEAT THE OTHER SIDE TOO''IF ITS READY PICK IT FROM THE PAN FOR EATING','add yummy ingredients')

    